version: "3.9"
services:
  app:
      build: .
      command: uvicorn app.app:app --host 0.0.0.0
      volumes:
        - .:/app
      ports:
        - "8000:8000"
      depends_on:
        - redis
  redis:
      image: "redis:alpine"
      ports:
        - "6379:6379"